import React from 'react';
import { Sparkles } from 'lucide-react';
import './TextSummary.css';

const TextSummary = ({ summary, ai_model }) => {
  return (
    <div className="summary-section glass-panel">
      <div className="section-header">
        <Sparkles size={24} color="var(--brand-purple)" />
        <h3>AI Summary</h3>
      </div>
      <p className="summary-text">{summary}</p>
      <div className="model-badge">Generated by {ai_model}</div>
    </div>
  );
};

export default TextSummary;
