import React from 'react';
import { Sparkles, CheckCircle2 } from 'lucide-react';
import './TextSummary.css';

const TextSummary = ({ summary, ai_model }) => {
  if (!summary) return null;

  const rawLines = summary.split('\n').map(l => l.trim()).filter(Boolean);

  const bulletItems = rawLines.map(line => {
    return line.replace(/^[\-*•\d.]+\s*/, '').trim();
  }).filter(line => line.length > 0);

  return (
    <div className="summary-section glass-panel">
      <div className="section-header">
        <Sparkles size={24} color="var(--brand-purple)" />
        <h3>Executive AI Summary</h3>
      </div>

      {bulletItems.length > 1 ? (
        <ul className="summary-bullets-list" style={{ listStyle: 'none', padding: 0, margin: '16px 0', display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {bulletItems.map((item, idx) => (
            <li key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', fontSize: '0.92rem', lineHeight: '1.5', color: 'var(--text-primary)' }}>
              <CheckCircle2 size={16} color="var(--brand-purple)" style={{ flexShrink: 0, marginTop: '3px' }} />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="summary-text">{summary}</p>
      )}

      <div className="model-badge">Generated by {ai_model}</div>
    </div>
  );
};

export default TextSummary;
