import React from 'react';
import ReactWordcloud from 'react-wordcloud';
import { Sparkles, FileText, BarChart2 } from 'lucide-react';
import './TextView.css';

const TextView = ({ textData }) => {
  const { summary, keywords, word_count, page_count, paragraph_count, ai_model } = textData;

  // Transform keywords into Wordcloud format: { text, value }
  const wordCloudData = keywords.map(kw => ({
    text: kw.word,
    value: kw.score * 100 // Scale up score for visualization
  }));

  const wordCloudOptions = {
    colors: ['#818cf8', '#6366f1', '#4f46e5', '#a855f7', '#d8b4fe'],
    enableTooltip: true,
    deterministic: false,
    fontFamily: 'Inter, sans-serif',
    fontSizes: [20, 60],
    fontStyle: 'normal',
    fontWeight: 'bold',
    padding: 1,
    rotations: 3,
    rotationAngles: [0, 90],
    scale: 'sqrt',
    spiral: 'archimedean',
    transitionDuration: 1000
  };

  return (
    <div className="text-view">
      
      {/* Top Level Metrics */}
      <div className="metrics-grid">
        <div className="metric-card glass-panel">
          <span className="metric-title">Word Count</span>
          <span className="metric-value">{word_count?.toLocaleString() || 0}</span>
        </div>
        {page_count !== null && page_count !== undefined && (
          <div className="metric-card glass-panel">
            <span className="metric-title">Pages Extracted</span>
            <span className="metric-value">{page_count}</span>
          </div>
        )}
        {paragraph_count !== null && paragraph_count !== undefined && (
          <div className="metric-card glass-panel">
            <span className="metric-title">Paragraphs</span>
            <span className="metric-value">{paragraph_count}</span>
          </div>
        )}
      </div>

      <div className="text-content-grid">
        {/* AI Summary Card */}
        <div className="summary-section glass-panel">
          <div className="section-header">
            <Sparkles size={24} color="var(--accent-color)" />
            <h3>AI Summary</h3>
          </div>
          <p className="summary-text">{summary}</p>
          <div className="model-badge">Generated by {ai_model}</div>
        </div>

        {/* Wordcloud Card */}
        <div className="wordcloud-section glass-panel">
          <div className="section-header">
            <BarChart2 size={24} color="var(--accent-color)" />
            <h3>Keyword Analysis</h3>
          </div>
          
          <div className="wordcloud-wrapper">
            {wordCloudData.length > 0 ? (
              <ReactWordcloud words={wordCloudData} options={wordCloudOptions} />
            ) : (
              <div className="no-keywords">No keywords found.</div>
            )}
          </div>
          
          {/* Keyword tags below the wordcloud */}
          <div className="keyword-tags">
            {keywords.slice(0, 10).map((kw, idx) => (
              <span key={idx} className="keyword-tag">
                {kw.word} <span className="score">{(kw.score * 100).toFixed(0)}%</span>
              </span>
            ))}
          </div>
        </div>
      </div>
      
    </div>
  );
};

export default TextView;
